### ISSUE TITLE
Will it work with Wikidata ?

### ISSUE THREAD

**Issue by teolemon** [flikkr/dartpedia#1]
Will it work with Wikidata items (Q42…) ? If so, would an example be possible ?

**Comment by flikkr** [comment]
Hi @teolemon, unfortunately I can't say for certain as I'm not sure what the API structure for Wikidata looks like.

**Comment by teolemon** [comment]
here's an example. There might be some common concept, but also many different things due to the structured nature of data:
https://www.wikidata.org/wiki/Q42
https://www.wikidata.org/wiki/Special:EntityData/Q42.json

https://www.wikidata.org/wiki/Wikidata:Data_access

**Comment by flikkr** [comment]
You're right, in its current state it won't be able to fetch from Wikidata, but I don't think it should be too difficult to adapt it and get it to work. Feel free to create a pull request if you want to contribute to the package.

**Comment by teolemon** [comment]
Ok, I just found by pure chance this package, not published to pub.dev. 
https://github.com/PanoptikumIO/wikidata_client/issues/1
